### ISSUE TITLE
Feature request: Atom feed

### ISSUE THREAD

**Issue by skybert** [christianhg/hamburger.cloud#1]
Love your articles man. Would be great if you could add an RSS or Atom feed to your website as well for easy consumption through a news aggregator such as Feedly or The Old Reader.

Cheers!

-Torstein

**Comment by christianhg** [comment]
Thank you so much, Torstein. I've never been a consumer of such feeds, but I've added an RSS feed now. Can you confirm that it is discoverable and readable?

**Comment by skybert** [comment]
Christian Hamburger Grøngaard writes:

> Thank you so much, Torstein. I've never been a consumer of such feeds,
> but I've added an RSS feed now. Can you confirm that it is
> discoverable and readable?

Confirmed. It's both discoverable and renders beautifully.

**Comment by christianhg** [comment]
Perfect :)
